### ISSUE TITLE
Violation of Content Security Policy directive: "default-src self"

### ISSUE THREAD

**Issue by jcnovoa** [TTEC-Dig-VF/Amazon-Connect-Chat-Translate-Demo#2]
Even after adding master.XYZ.amplifyapp.com to the Amazon Connect instance approved origins list, and ensuring the right REACT_APP_CONNECT_INSTANCE_URL Env. Vars were set (without extra spaces) + a rebuild, we still get the following error:

Refused to execute inline script because it violates the following Content Security Policy directive: "default-src self". Either the 'unsafe-inline' keyword, a hash ('sha256-TcxCqm3IAZb7lwb/jIKWl56mO4KCckyb4BUJD45PFNs='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

master.XYZ.amplifyapp.com/:1 Refused to load the script 'https://master.XYZ.amplifyapp.com/static/js/3.b650f316.chunk.js' because it violates the following Content Security Policy directive: "default-src self". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by DanBloy** [comment]
This was due to Amplify security headers. I've removed 

`- key: 'Content-Security-Policy'
     value: 'default-src self'`

from `customHttp.yml`

@jcnovoa, please pull down the latest code and redeploy

**Comment by jcnovoa** [comment]
Thank you @DanBloy that did it; pretty AWSome demo, worked like a charm!
